<?php

namespace AppBundle\Repository\Acteurs;

/**
 * TypeUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
