<?php

namespace Neosolva\SI\DocsBundle\Repository\Acteurs;

/**
 * AccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesRepository extends \Doctrine\ORM\EntityRepository
{
}
