<?php

namespace Newer\SI\DocsBundle\Repository\Acteurs;

/**
 * AttributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionRepository extends \Doctrine\ORM\EntityRepository
{
}
