<?php

namespace Newer\SI\DocsBundle\Repository\Acteurs;

/**
 * TypeAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAccesRepository extends \Doctrine\ORM\EntityRepository
{
}
