<?php

namespace Neosolva\SI\DocsBundle\Repository\Document;

/**
 * ParagrapheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParagrapheRepository extends \Doctrine\ORM\EntityRepository
{
}
